export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_USUARIOS= 'OBTENER_USUARIO';
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const VERIFICAR_USUARIO = 'VERIFICAR_USUARIO';
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const CREAR_USUARIO = 'CREAR_USUARIO';
export const CARGAR_USUARIO = 'CARGAR_USUARIO';

export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO';
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const ACTUALIZAR_PRODUCTO = 'ACTUALIZAR_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const CREAR_PRODUCTO = 'CREAR_PRODUCTO';

export const OBTENER_WISH_LIST = 'OBTENER_WISH_LIST';
export const ACTUALIZAR_ITEM_WISH_LIST = 'ACTUALIZAR_ITEM_WISH_LIST';
export const ACTUALIZAR_WISH_LIST = 'ACTUALIZAR_WISH_LIST';
export const ELIMINAR_ITEM_WISH_LIST = 'ELIMINAR_ITEM_WISH_LIST';
export const ELIMINAR_WISH_LIST = 'ELIMINAR_WISH_LIST';
export const CREAR_WISH_LIST = 'CREAR_WISH_LIST';
export const ADD_ITEM_WISH_LIST = 'ADD_ITEM_WISH_LIST';
export const CARGANDO_WISH_LIST = 'CARGANDO_WISH_LIST';


export const OBTENER_LIST_PRODUCT_WISH_LIST = 'OBTENER_LIST_PRODUCT_WISH_LIST';

export const ACTIVE_TOGGLE = 'ACTIVE_TOGGLE';
export const CAMBIAR_PAGINA = 'CAMBIAR_PAGINA';